# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestMovieSearch():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_movieSearch(self):
        self.driver.get("http://127.0.0.1:5500/home.html")
        self.driver.set_window_size(1380, 875)
        self.driver.find_element(By.ID, "searchInput").click()
        self.driver.find_element(
            By.ID, "searchInput").send_keys("the green mile")
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(2)
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "html").click()
        self.driver.find_element(By.ID, "searchInput").clear()
        time.sleep(2)
        self.driver.find_element(
            By.ID, "searchInput").send_keys("Interstellar")
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        self.driver.find_element(By.ID, "searchInput").click()
        time.sleep(2)
        self.driver.close()
